[settings]
go_set_gobin = false

[tools]
node = "24.11.1"
pnpm = "10"
npm = "latest"

"npm:gitmoji-cli" = "latest"
"ubi:goreleaser/goreleaser" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:sharkdp/bat" = "latest"
"github:k1LoW/mo" = "0.20.2"
"npm:neovim" = "latest"
"npm:prettier" = "latest"
"npm:cspell" = "latest"
"aqua:neovim/neovim" = "latest"
python = "3.12"
fzf = "latest"
starship = "latest"
ghq = "latest"
lazygit = "latest"
delta = "latest"
zig = "latest"
fd = "latest"
gh = "latest"
go = "latest"
jq = "latest"
glab = "latest"
uv = "latest"
bun = "latest"
rust = "latest"
"npm:difit" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
dotnet = "10"

